### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by blackjackyau** [yihtserns/scripts#1]
dunno what arguments it takes

**Comment by yihtserns** [comment]
Which script are you referring to?

**Comment by blackjackyau** [comment]
since there are multiple scripts i think a consolidated examples on how to use them would be good

**Comment by yihtserns** [comment]
Since you're mainly talking about `findjar.groovy`, just run it and it'll spit out the instructions.

**Comment by blackjackyau** [comment]
lol
